# -------- Build Stage --------
FROM node:18-alpine AS builder

WORKDIR /app

# Copy entire frontend folder
COPY frontend/ .

# Install dependencies
RUN npm install

# Build production app
RUN npm run build


# -------- Production Stage --------
FROM nginx:alpine

# Copy built files from builder
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy custom nginx config for API reverse proxy
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
